language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .[dev]
# command to run tests
script: nosetests --with-coverage --cover-erase

after_success:
  - codecov
